// src/data/DepartmentOptions.js
export const departmentOptions = [
    { value: "Examination Section", label: "Examination Section" },
    { value: "Registrar Office", label: "Registrar Office" },
    { value: "Administration Section", label: "Administration Section" },
    { value: "Human Resource Section", label: "Human Resource Section" },
    { value: "Store Section", label: "Store Section" },
    { value: "Caretaking Section", label: "Caretaking Section" },
    { value: "Purchase Section", label: "Purchase Section" },
    { value: "Account Section", label: "Account Section" },
    { value: "Finance Section", label: "Finance Section" },
    { value: "Right to information Section", label: "Right to information Section" },
    { value: "Information Technology Section", label: "Information Technology Section" },
    { value: "Recruitment Section", label: "Recruitment Section" },
    { value: "Liasion Section - OBC", label: "Liasion Section - OBC" },
    { value: "Liasion Section - SC/ST/PwD", label: "Liasion Section - SC/ST/PwD" },
    { value: "Partnership Section", label: "Partnership Section" },
    { value: "Department of Agri Business Management", label: "Department of Agri Business Management" },
    { value: "Department of Dairy Management", label: "Department of Dairy Management" },
    { value: "Department of Farmhouse Management", label: "Department of Farmhouse Management" },
    { value: "Department of Forestry", label: "Department of Forestry" },
    { value: "Department of Organic Farming and Crop Management", label: "Department of Organic Farming and Crop Management" },
    { value: "Department of Poultry Farm Management", label: "Department of Poultry Farm Management" },
    { value: "Department of Vertical Farming", label: "Department of Vertical Farming" },
    { value: "Department of Allied Medical Science", label: "Department of Allied Medical Science" },
    { value: "Department of Allied Health Care Science", label: "Department of Allied Health Care Science" },
    { value: "Department of Pharmaceutical Science", label: "Department of Pharmaceutical Science" },
    { value: "Department of Optometry & Vision Science", label: "Department of Optometry & Vision Science" },
    { value: "Department of Rehabilitation Science", label: "Department of Rehabilitation Science" },
    { value: "Department of Crafts Design", label: "Department of Crafts Design" },
    { value: "Department of Digital Media Design", label: "Department of Digital Media Design" },
    { value: "Department of Fashion Design", label: "Department of Fashion Design" },
    { value: "Department of Garment Fabrication Technology", label: "Department of Garment Fabrication Technology" },
    { value: "Department of Gems and Jewellery Design", label: "Department of Gems and Jewellery Design" },
    { value: "Department of Product Design", label: "Department of Product Design" },
    { value: "Department of Fine Arts", label: "Department of Fine Arts" },
    { value: "Department of Performing Arts", label: "Department of Performing Arts" },
    { value: "Department of Social Media Management", label: "Department of Social Media Management" },
    { value: "Department of Interior Design", label: "Department of Interior Design" },
    { value: "Department of Architecture", label: "Department of Architecture" },
    { value: "Department of Civil Engineering", label: "Department of Civil Engineering" },
    { value: "Department of Urban Infrastructure And Planning", label: "Department of Urban Infrastructure And Planning" },
    { value: "Department of Banking, Financial Services and Insurance", label: "Department of Banking, Financial Services and Insurance" },
    { value: "Department of Business Administration", label: "Department of Business Administration" },
    { value: "Department of Business Process Management", label: "Department of Business Process Management" },
    { value: "Department of Economics", label: "Department of Economics" },
    { value: "Department of E-Commerce", label: "Department of E-Commerce" },
    { value: "Department of Human Resource Management", label: "Department of Human Resource Management" },
    { value: "Department of International Business Management", label: "Department of International Business Management" },
    { value: "Department of Office Management (MOP)", label: "Department of Office Management (MOP)" },
    { value: "Department of Retail Management", label: "Department of Retail Management" },
    { value: "Department of Warehouse Management", label: "Department of Warehouse Management" },
    { value: "Department of Supply Chain Management", label: "Department of Supply Chain Management" },
    { value: "Department of Physics", label: "Department of Physics" },
    { value: "Department of Chemistry", label: "Department of Chemistry" },
    { value: "Department of Mathematics", label: "Department of Mathematics" },
    { value: "Department of Statistics", label: "Department of Statistics" },
    { value: "Department of Life Sciences", label: "Department of Life Sciences" },
    { value: "Department of Chemical Engineering", label: "Department of Chemical Engineering" },
    { value: "Department of Petrochemicals", label: "Department of Petrochemicals" },
    { value: "Department of Polymer Science and Technology", label: "Department of Polymer Science and Technology" },
    { value: "Department of Metallurgy and Mining", label: "Department of Metallurgy and Mining" },
    { value: "Department of Artificial Intelligence and Machine Learning", label: "Department of Artificial Intelligence and Machine Learning" },
    { value: "Department of Augmented Reality", label: "Department of Augmented Reality" },
    { value: "Department of Computer Engineering", label: "Department of Computer Engineering" },
    { value: "Department of Computer Science and Application", label: "Department of Computer Science and Application" },
    { value: "Department of Data Analytics", label: "Department of Data Analytics" },
    { value: "Department of Library and Information Science", label: "Department of Library and Information Science" },
    { value: "Department of Virtual Reality", label: "Department of Virtual Reality" },
    { value: "Department of Biosystem Inspired Engineering", label: "Department of Biosystem Inspired Engineering" },
    { value: "Department of Biotechnology and Bioinformatics", label: "Department of Biotechnology and Bioinformatics" },
    { value: "Department of Computer Aided Drug Design", label: "Department of Computer Aided Drug Design" },
    { value: "Department of Cognitive Neuroscience", label: "Department of Cognitive Neuroscience" },
    { value: "Department of DRONE Technologies", label: "Department of DRONE Technologies" },
    { value: "Department of Nanotechnology", label: "Department of Nanotechnology" },
    { value: "Department of Nano-Biosensor Technologies", label: "Department of Nano-Biosensor Technologies" },
    { value: "Department of Natural Language Programming", label: "Department of Natural Language Programming" },
    { value: "Department of Quantum Technologies", label: "Department of Quantum Technologies" },
    { value: "Department of Quantum Computing", label: "Department of Quantum Computing" },
    { value: "Department of Sustainability Science", label: "Department of Sustainability Science" },
    { value: "Department of Electrical Engineering", label: "Department of Electrical Engineering" },
    { value: "Department of Electronics Communication Engineering", label: "Department of Electronics Communication Engineering" },
    { value: "Department of Instrumentation and Control Engineering", label: "Department of Instrumentation and Control Engineering" },
    { value: "Department of Internet of Things (IoT)", label: "Department of Internet of Things (IoT)" },
    { value: "Department of Networking and Security Informatics", label: "Department of Networking and Security Informatics" },
    { value: "Department of Innovation Entrepreneurship", label: "Department of Innovation Entrepreneurship" },
    { value: "Department of Intrapreneurship", label: "Department of Intrapreneurship" },
    { value: "Department of Small Business Entrepreneurship", label: "Department of Small Business Entrepreneurship" },
    { value: "Department of Social Entrepreneurship", label: "Department of Social Entrepreneurship" },
    { value: "Department of Start-up Entrepreneurship", label: "Department of Start-up Entrepreneurship" },
    { value: "Department of Customer Service Management", label: "Department of Customer Service Management" },
    { value: "Department of English", label: "Department of English" },
    { value: "Department of French", label: "Department of French" },
    { value: "Department of German", label: "Department of German" },
    { value: "Department of Hindi", label: "Department of Hindi" },
    { value: "Department of Japanese", label: "Department of Japanese" },
    { value: "Department of Journalism", label: "Department of Journalism" },
    { value: "Department of Mandarin (Chinese)", label: "Department of Mandarin (Chinese)" },
    { value: "Department of Russian", label: "Department of Russian" },
    { value: "Department of Spanish", label: "Department of Spanish" },
    { value: "Department of Korean Language", label: "Department of Korean Language" },
    { value: "Department of Automobile Engineering", label: "Department of Automobile Engineering" },
    { value: "Department of Mechanical Engineering", label: "Department of Mechanical Engineering" },
    { value: "Department of Mechatronics", label: "Department of Mechatronics" },
    { value: "Department of Printing and Packaging Technology", label: "Department of Printing and Packaging Technology" },
    { value: "Department of Robotics and Automation", label: "Department of Robotics and Automation" },
    { value: "Department of Tool and Production Engineering", label: "Department of Tool and Production Engineering" },
    { value: "Department of Gym Management", label: "Department of Gym Management" },
    { value: "Department of Psychology", label: "Department of Psychology" },
    { value: "Department of Relationship Management", label: "Department of Relationship Management" },
    { value: "Department of Sports Management", label: "Department of Sports Management" },
    { value: "Department of Yoga, Wellness and Meditation", label: "Department of Yoga, Wellness and Meditation" },
    { value: "Department of Aesthetics & Beauty", label: "Department of Aesthetics & Beauty" },
    { value: "Department of Cosmetology", label: "Department of Cosmetology" },
    { value: "Department of Event Management", label: "Department of Event Management" },
    { value: "Department of Food Production", label: "Department of Food Production" },
    { value: "Department of Front Office Management", label: "Department of Front Office Management" },
    { value: "Department of Facility Management", label: "Department of Facility Management" },
    { value: "Department of Home Science", label: "Department of Home Science" },
    { value: "Department of Hospital Facility Management", label: "Department of Hospital Facility Management" },
    { value: "Department of Hotel Management", label: "Department of Hotel Management" },
    { value: "Department of Tourism and Cultural Affairs", label: "Department of Tourism and Cultural Affairs" },
  ];