
export const designationOptions = [
  { value: "vice-chancellor", label: "Vice Chancellor" },
  { value: "pro-vice-chancellor", label: "Pro Vice Chancellor" },
  { value: "registrar", label: "Registrar" },
  { value: "controller-examinations", label: "Controller Of Examinations" },
  { value: "controller-finance", label: "Controller Of Finance" },
  { value: "dean", label: "Dean" },
  { value: "director-student-welfare", label: "Director Student Welfare" },
  { value: "joint-director-it", label: "Joint Director - Information Technology" },
  { value: "joint-director-academics", label: "Joint Director - Academics" },
  { value: "joint-director-partnership", label: "Joint Director - Patnership" },
  { value: "campus-director", label: "Campus Director" },
  { value: "professor", label: "Professor" },
  { value: "associate-professor", label: "Associate Professor" },
  { value: "assistant-professor", label: "Assistant Professor" },
  { value: "lecturer", label: "Lecturer" },
  { value: "distinguished-professor", label: "Distinguished Professor" },
  { value: "emeritus-professor", label: "Emeritus Professor" },
  { value: "hod", label: "Head Of Department" },
  { value: "deputy-registrar", label: "Deputy Registrar" },
  { value: "assistant-registrar", label: "Assistant Registrar" },
  { value: "deputy-controller-accounts", label: "Deputy Controller Of Accounts" },
  { value: "executive-engineer", label: "Executive Engineer" },
  { value: "assistant-director", label: "Assistant Director" },
  { value: "training-placement-officer", label: "Training & Placement Officer" },
  { value: "system-analyst", label: "System Analyst" },
  { value: "assistant-engineer", label: "Assistant Engineer" },
  { value: "junior-engineer", label: "Junior Engineer" },
  { value: "junior-office-assistant", label: "Junior Office Assistant" },
  { value: "senior-accounts-officer", label: "Senior Accounts Officer" },
  { value: "accounts-officer", label: "Accounts Officer" },
  { value: "assistant-accounts-officer", label: "Assistant Accounts Officer" },
  { value: "assistant-section-officer", label: "Assistant Section Officer" },
  { value: "office-superintendent", label: "Office Superintendent" },
  { value: "personal-secretary", label: "Personal Secretary" },
  { value: "stenographer", label: "Stenographer" },
  { value: "senior-assistant", label: "Senior Assistant" },
  { value: "junior-assistant", label: "Junior Assistant/ Office Assistant" },
  { value: "foreman-instructor", label: "Foreman Instructor" },
  { value: "section-officer", label: "Section Officer" },
  { value: "account-officer", label: "Account Officer" },
  { value: "librarian", label: "Librarian" },
  { value: "assistant-librarian", label: "Assistant Librarian" },
  { value: "pti", label: "Physical Training Instructor" },
  { value: "workshop-superintendent", label: "Workshop Superintendent" },
  { value: "workshop-instructor", label: "Workshop Instructor" },
  { value: "security-officer", label: "Security Officer" },
  { value: "caretaker", label: "Caretaker" },
  { value: "technical-assistant", label: "Technical Assistant" },
  { value: "workshop-assistant", label: "Workshop Assistant" },
  { value: "hostel-superintendent", label: "Hostel Superintendent" },
  { value: "store-officer", label: "Store Officer" },
  { value: "store-keeper", label: "Store Keeper" },
  { value: "junior-technician", label: "Junior Technician" },
  { value: "senior-technician", label: "Senior Technician" },
  { value: "technician", label: "Technician" },
  { value: "electrician", label: "Electrician" },
  { value: "mechanic", label: "Mechanic" },
  { value: "instrument-repairer", label: "Instrument Repairer" },
  { value: "junior-mechanic", label: "Junior Mechanic" },
  { value: "lab-attendant", label: "Laboratory Attendant" },
  { value: "cad-draftsman", label: "Cad/Draftsman" },
  { value: "senior-mechanic", label: "Senior Mechanic" },
  { value: "udc", label: "Upper Division Clerk" },
  { value: "workshop-attendant", label: "Workshop Attendant" },
  { value: "mts", label: "Multi Tasking Staff (MTS)" },
  { value: "driver-outsourced", label: "Driver (On Outsource Basis)" },
  { value: "osd", label: "Officer on Special Duty" },
  { value: "pio", label: "Public Information Officer" },
  { value: "liaison-obc", label: "Liaision officer - OBC" },
  { value: "liaison-scstpwd", label: "Liaison officer - SC/ST/PwD" },
  { value: "fi-admin", label: "Faculty Incharge - Admin" },
  { value: "fi-caretaking", label: "Faculty Incharge - Caretaking" },
  { value: "fi-exam", label: "Faculty Incharge - Exam" },
  { value: "fi-purchase", label: "Faculty Incharge - Purchase" },
  { value: "fi-student-activity", label: "Faculty Incharge - Student Activity" },
  { value: "fi-it", label: "Faculty Incharge - Information Technology" },
  { value: "fi-department", label: "Faculty Incharge - Respective Department" },
];
