const regulations = [
    {
        id: "2B",
        name: "Regulation 2B",
        link: "/regulations/Regulation_2B.pdf",
        desc: "This regulation pertains to Composition and functions of Board of Studies and Committee of Courses.",
    },
    {
        id: "3C",
        name: "Regulation 3C",
        link: "/regulations/Regulation_3C.pdf",
        desc: "This covers various skill programs (Technical, Vocational, Entrepreneurship, and Academic) and officially notified master’s programs, including a two-year (four-semester) Master’s in a major discipline, MBA, and one-year MS/MTech. It is based on Regulation 2-A.",
    },
    {
        id: "3A",
        name: "Regulation 3A",
        link: "/regulations/Regulation_3A.pdf",
        desc: "Regulation for Three Year Diploma (Technical) (NCrF level 4.5) in a Major Discipline.",
    },
    {
        id: "3B",
        name: "Regulation 3B",
        link: "/regulations/Regulation_3B.pdf",
        desc: "This regulation covers three-year (six semesters) and four-year (eight semesters) bachelor's degrees (major and minor) under TSP, VSP, ESP, and ASP, based on Regulation 2-A.",
    },
];

export { regulations };