const regulations = [
    {
        id: "2B",
        name: "Regulation 2B",
        link: "/regulations/Regulation_2B.pdf",
        desc: "Comprehensive academic policies for batch 2022 onwards.",
    },
    {
        id: "3C",
        name: "Regulation 3C",
        link: "/regulations/Regulation_3C.pdf",
        desc: "Updated credit system and assessment criteria.",
    },
    {
        id: "3A",
        name: "Regulation 3A",
        link: "/regulations/Regulation_3A.pdf",
        desc: "Guidelines on research and multidisciplinary projects.",
    },
    {
        id: "3B",
        name: "Regulation 3B",
        link: "/regulations/Regulation_3B.pdf",
        desc: "Policies for flexible exit options and certifications.",
    },
];

export { regulations };