const regulations = [
    {
        id: "1",
        name: "Regulation 1 (I)",
        link: "/regulations/Regulation_1.pdf",
        desc: "This regulation contains the names of faculties and departments.",
    },
    {
        id: "2A",
        name: "Regulation 2A",
        link: "/regulations/Regulation_2A.pdf",
        desc: "This regulation Covers CBCS, semester system, entry/exit options, and grading as per NEP 2020 at DSEU from 2024–25.",
    },
    {
        id: "3A",
        name: "Regulation 3A",
        link: "/regulations/Regulation_3A.pdf",
        desc: "Regulation for Three Year Diploma (Technical) (NCrF level 4.5) in a Major Discipline.",
    },
    {
        id: "3B",
        name: "Regulation 3B",
        link: "/regulations/Regulation_3B.pdf",
        desc: "This regulation covers three-year (six semesters) and four-year (eight semesters) bachelor's degrees (major and minor) under TSP, VSP, ESP, and ASP, based on Regulation 2-A.",
    },
    {
        id: "3C",
        name: "Regulation 3C",
        link: "/regulations/Regulation_3C.pdf",
        desc: "This covers various skill programs (Technical, Vocational, Entrepreneurship, and Academic) and officially notified master’s programs, including a two-year (four-semester) Master’s in a major discipline, MBA, and one-year MS/MTech. It is based on Regulation 2-A.",
    },
];

export { regulations };