const antiRagging = {
  introText:
    "The Anti-Ragging Cell ensures a safe and welcoming environment on campus by actively monitoring student interactions, conducting awareness programs, and addressing grievances promptly. We are committed to fostering a culture of mutual respect, inclusivity, and support, where every student can learn and grow without fear or intimidation.",
    whatIsRagging: [
      "Ragging refers to any act of physical or psychological abuse directed at a student, often disguised as a form of 'introduction' or 'interaction' by senior students.",
      "It encompasses behavior that induces embarrassment, fear, or humiliation, including name-calling, coercive tasks, or verbal harassment.",
      "Ragging may manifest in physical, emotional, or psychological forms and can involve threats, social isolation, or misuse of authority.",
      "It infringes upon the dignity and rights of students and is recognized as a punishable offense under the law and institutional regulations."
    ],
    
    actionsAgainstRagging: [
      "Immediate suspension of students found to be involved in ragging, pending the outcome of an investigation.",
      "A thorough investigation conducted by the Anti-Ragging Cell to identify all individuals responsible and ensure accountability.",
      "Provision of counseling and psychological support to victims of ragging to aid in their recovery from the trauma.",
      "Initiation of legal proceedings against offenders, including criminal prosecution in accordance with applicable laws."
    ],
    
  pdfLinks: [
    {
      name: "Affidavit by Parent",
      url: "/anti_ragging/Affidavit-by-Parent.pdf"
    },
    {
      name: "Affidavit by Student",
      url: "/anti_ragging/Affidavit-by-Student.pdf"
    },
    {
      name: "UGC Regulations on Ragging",
      url: "/anti_ragging/Anti-Ragging-Rules-UGC.pdf"
    },
    {
      name: "Supreme Court Guidelines",
      url: "/anti_ragging/Honourable-Supreme-Court-of-india-judgement.pdf"
    }
  ]
};

export { antiRagging };
