import { registarar, VC } from '../assets/advisory-board';
import { jpSaini, deshmukh, girishKumar, vivekAggrawal, vibhakarShrimali, kamnaSachdeva, shrutiTripathi, dttesecratory, placeholder, njena, principalSecratory } from '../assets/board-of-management/boardOfManagement';
const boardOfManagement = [
    {
        id: 1,
        name: "Prof. Ashok Kumar Nagawat",
        designation: "Vice-Chancellor",
        category: "Chairperson",
        src: VC,
    },
    {
        id: 2,
        name: "Mr. Vivek Agarwal",
        designation: "Member Secretary",
        category: "Registrar",
        src: vivekAggrawal,
    },
    {
        id: 3,
        name: "Prof. Gagan Dhawan",
        category: "Deans",
        src: registarar,
    },
    {
        id: 4,
        name: "Prof. J.P. Saini",
        designation: "Representative AICTE",
        category: "Representatives",
        src: jpSaini,
    },
    {
        id: 5,
        name: "Prof. S. G. Deshmukh",
        designation: "Representative UGC",
        category: "Representatives",
        src: deshmukh,
    },
    {
        id: 6,
        name: "Prof. Girish Kumar",
        category: "Deans",
        src: girishKumar,
    },
    {
        id: 8,
        name: "Prof. Kamna Sachdeva",
        category: "Deans",
        src: kamnaSachdeva,
    },
    {
        id: 7,
        name: "Prof. Vibhakar Shrimali",
        category: "Deans",
        src: vibhakarShrimali,
    },

    {
        id: 10,
        name: "Prof. N Jena",
        category: "HoD",
        src: njena,
    },
    {
        id: 9,
        name: "Prof. Shruti Tripathi",
        category: "HoD",
        src: shrutiTripathi,
    },
    {
        id: 12,
        name: "Sh. Ashish Chandra Verma, IAS",
        designation: "Principal Secretary Finance",
        category: "Secretaries",
        src: principalSecratory,
    },
    {
        id: 11,
        name: "Ms. Nandini Paliwal",
        designation: "Secretary DTTE",
        category: "Secretaries",
        src: dttesecratory,
    }
];


export { boardOfManagement };