import { registarar, VC } from '../assets/advisory-board';
import { jpSaini, deshmukh, girishKumar, vivekAggrawal, vibhakarShrimali, kamnaSachdeva, shrutiTripathi,dttesecratory, placeholder } from '../assets/board-of-management/boardOfManagement';

const boardOfManagement = [
    {
        id: 1,
        name: "Prof. Ashok Kumar Nagawat",
        designation: "Vice-Chancellor",
        category: "Chairperson",
        src: VC,
    },
    {
        id: 2,
        name: "Mr. Vivek Agarwal",
        category: "Registrar",
        src: vivekAggrawal,
    },
    {
        id: 2,
        name: "Prof. (Dr.) Gagan Dhawan",
        category: "Deans",
        src: registarar,
    },
    {
        id: 3,
        name: "Prof. J.P. Saini",
        designation: "Representative AICTE",
        category: "Representative",
        src: jpSaini,
    },
    {
        id: 4,
        name: "Prof. S. G. Deshmukh",
        designation: "Representative UGC",
        category: "Representative",
        src: deshmukh,
    },
    {
        id: 5,
        name: "Prof. Girish Kumar",
        category: "Deans",
        src: girishKumar,
    },
    {
        id: 5,
        name: "Prof. Vibhakar Shrimali",
        category: "Deans",
        src: vibhakarShrimali,
    },
    {
        id: 5,
        name: "Prof. Kamna Sachdeva",
        category: "Deans",
        src: kamnaSachdeva,
    },
    {
        id: 5,
        name: "Prof. Shruti Tripathi",
        category: "HoD",
        src: shrutiTripathi,
    },
    {
        id: 5,
        name: "Prof. N Jena",
        category: "HoD",
        src: placeholder,
    },
    {
        id: 8,
        name: "Ms. Nandini Paliwal",
        designation: "Secretary DTTE",
        category: "Secretary",
        src: dttesecratory,
    },
    {
        id: 8,
        name: "Sh. Ashish Chandra Verma, IAS",
        designation: "Principal Secretary Finance",
        category: "Secretary",
        src: placeholder,
    }
];


export { boardOfManagement };