// import Shakarpur from "../assets/Shakarpur.jpg";
// import shakarpur2 from "../assets/shakarpur2.jpg";
// import MayurVihar from "../assets/MayurVihar.jpg";
// import VivekVihar from "../assets/VivekVihar.jpg";

// const images = [
//     {
//         src: Shakarpur,
//         alt: "Card 1",
//         text: " DSEU Shakarpur Campus",
//         address: "MB 153/B, opp. Madhuvan Park, Ganesh Nagar Extn - 2, Shakarpur, Delhi, 110092",
//         link: "/BPIBS",
//     },
//     {
//         src: shakarpur2,
//         alt: "Card 2",
//         text: "DSEU Shakarpur 2 Campus",
//         address: "MB 153/B, opp. Madhuvan Park, Ganesh Nagar Extn - 2, Shakarpur, Delhi, 110092",
//         link: "/shakarpur",
//     },
//     {
//         src: MayurVihar,
//         alt: "Card 3",
//         text: "DSEU Mayur Vihar Campus",
//         address: "J77W+4VJ, Sanjay Lake View Apartments, Pocket 5, Mayur Vihar, New Delhi, Delhi 110091",
//         link: "/Mayurvihar",
//     },
//     {
//         src: VivekVihar,
//         alt: "Card 4",
//         text: "DSEU Vivek Vihar Campus",
//         address: "ITI COLLEGE, Vivek Vihar Rd, Block C, Vivek Vihar Phase I, Vivek Vihar, Delhi, 110095",
//         link: "/vivekvihar",
//     },
// ];

// export { images };