import bluestar from '../assets/alumni/blueStar.png';
import TCS from '../assets/alumni/TCS.png';
import MCdermott from '../assets/alumni/MCdermott.png';

export const events = [
    {
      date: "07",
      month: "JAN",
      location: "Lighthouse Point, FL | Social",
      title:
        "Celebrating Achievements with BlueStar: A Night of Networking and Fun!",
      organization: "BlueStar Alumni Network",
      image: bluestar, // Specify image for this event
    },
    {
      date: "14",
      month: "JAN",
      location: "Miami, FL | Networking",
      title:
        "Tech Innovators Meetup: Future Insights Powered by TCS",
      organization: "TCS Global Network",
      image: TCS, // Specify image for this event
    },
    {
      date: "21",
      month: "JAN",
      location: "Fort Lauderdale, FL | Conference",
      title:
        "MCdermott Presents: Exploring AI and Machine Learning in the Real World",
      organization: "MCdermott Technology Group",
      image: MCdermott, // Specify image for this event
    },
  ];