const diplomaPrograms = [
    {
        title: "Diploma in Automobile Engineering ",
        code: "201100",
        campus: "BPIBS DSEU Campus-II",
        institute: "DSEU University India",
        university: "DSEU University India",
        eligibility: "X Passed with min. 50%",
        duration: "3 Years",
        fee: "₹10,000 per semester",
    },
    {
        title: "Diploma in Chemical Engineering ",
        code: "",
        campus: "BPIBS DSEU Campus-II",
        institute: "DSEU University India",
        university: "DSEU University India",
        eligibility: "X Passed with min. 50%",
        duration: "3 Years",
        fee: "₹10,000 per semester",
    },
    {
        title: "Diploma in Civil Engineering ",
        code: "",
        campus: "BPIBS DSEU Campus-II",
        institute: "DSEU University India",
        university: "DSEU University India",
        eligibility: "X Passed with min. 50%",
        duration: "3 Years",
        fee: "₹10,000 per semester",
    },
    {
        title: "Diploma in Computer Engineering",
        code: "",
        campus: "BPIBS DSEU Campus-II",
        institute: "DSEU University India",
        university: "DSEU University India",
        eligibility: "X Passed with min. 50%",
        duration: "3 Years",
        fee: "₹10,000 per semester",
    },
    {
        title: "Diploma in Electrical Engineering ",
        code: "",
        campus: "BPIBS DSEU Campus-II",
        institute: "DSEU University India",
        university: "DSEU University India",
        eligibility: "X Passed with min. 50%",
        duration: "3 Years",
        fee: "₹10,000 per semester",
    },
    {
        title: "Diploma in Electronics Engineering",
        code: "",
        campus: "BPIBS DSEU Campus-II",
        institute: "DSEU University India",
        university: "DSEU University India",
        eligibility: "X Passed with min. 50%",
        duration: "3 Years",
        fee: "₹10,000 per semester",
    },
    {
        title: "Diploma in Mechanical Engineering ",
        code: "",
        campus: "BPIBS DSEU Campus-II",
        institute: "DSEU University India",
        university: "DSEU University India",
        eligibility: "X Passed with min. 50%",
        duration: "3 Years",
        fee: "₹10,000 per semester",
    },
    {
        title: "Diploma in Petrochemicals ",
        code: "",
        campus: "BPIBS DSEU Campus-II",
        institute: "DSEU University India",
        university: "DSEU University India",
        eligibility: "X Passed with min. 50%",
        duration: "3 Years",
        fee: "₹10,000 per semester",
    },
    {
        title: "Diploma in Polymer Technology ",
        code: "",
        campus: "BPIBS DSEU Campus-II",
        institute: "DSEU University India",
        university: "DSEU University India",
        eligibility: "X Passed with min. 50%",
        duration: "3 Years",
        fee: "₹10,000 per semester",
    },
    {
        title: "  Diploma in Precision Engineering",
        code: "",
        campus: "BPIBS DSEU Campus-II",
        institute: "DSEU University India",
        university: "DSEU University India",
        eligibility: "X Passed with min. 50%",
        duration: "3 Years",
        fee: "₹10,000 per semester",
    },
    {
        title: "Diploma in Printing Technology ",
        code: "",
        campus: "BPIBS DSEU Campus-II",
        institute: "DSEU University India",
        university: "DSEU University India",
        eligibility: "X Passed with min. 50%",
        duration: "3 Years",
        fee: "₹10,000 per semester",
    },
    {
        title: " Diploma in Robotic and Process Automation",
        code: "",
        campus: "BPIBS DSEU Campus-II",
        institute: "DSEU University India",
        university: "DSEU University India",
        eligibility: "X Passed with min. 50%",
        duration: "3 Years",
        fee: "₹10,000 per semester",
    },
    {
        title: " Four Year UG Diploma in Tool and Die Making",
        code: "",
        campus: "BPIBS DSEU Campus-II",
        institute: "DSEU University India",
        university: "DSEU University India",
        eligibility: "X Passed with min. 50%",
        duration: "3 Years",
        fee: "₹10,000 per semester",
    },
    {
        title: " Diploma in Architecture ",
        code: "",
        campus: "BPIBS DSEU Campus-II",
        institute: "DSEU University India",
        university: "DSEU University India",
        eligibility: "X Passed with min. 50%",
        duration: "3 Years",
        fee: "₹10,000 per semester",
    },
]

const ugDiplomaPrograms = [
    {
        "title": "UG Diploma in Sports Fitness and Yoga Applications",
        "code": "201103",
        "campus": "DSEU Siri Fort Campus",
        "eligibility": "XII Passed with min. 60%",
        "duration": "2 Years",
        "fee": "INR 25,000 per semester"
    },
    {
        "title": "UG Diploma in Hospitality Operations",
        "code": "201103",
        "campus": "DSEU Siri Fort Campus",
        "eligibility": "XII Passed with min. 60%",
        "duration": "2 Years",
        "fee": "INR 25,000 per semester"
    },
    {
        "title": "UG Diploma in Beauty and Wellness",
        "code": "201103",
        "campus": "Ambedkar DSEU Shakarpur Campus-I",
        "eligibility": "XII Passed with min. 60%",
        "duration": "2 Years",
        "fee": "INR 10,000 per semester"
    },
    {
        "title": "UG Diploma in Electronics System Design & Manufacturing",
        "code": "201103",
        "campus": "Ambedkar DSEU Shakarpur Campus-I",
        "eligibility": "XII Passed with min. 60%",
        "duration": "2 Years",
        "fee": "INR 25,000 per semester"
    },
    {
        "title": "UG Diploma in Video Production",
        "code": "201103",
        "campus": "Bhai Parmanand DSEU Shakarpur-II",
        "eligibility": "XII Passed with min. 60%",
        "duration": "2 Years",
        "fee": "INR 50,000 per semester"
    },
    {
        "title": "UG Diploma in Precision Engineering",
        "code": "201103",
        "campus": "Aryabhatt DSEU Ashok Vihar",
        "eligibility": "XII Passed with min. 60%",
        "duration": "2 Years",
        "fee": "INR 25,000 per semester"
    },
    {
        "title": "UG Diploma in Garment Manufacturing and Quality Assurance",
        "code": "201103",
        "campus": "Aryabhatt DSEU Ashok Vihar",
        "eligibility": "XII Passed with min. 60%",
        "duration": "2 Years",
        "fee": "INR 25,000 per semester"
    },
    {
        "title": "UG Diploma in Tool and Die Making",
        "code": "201103",
        "campus": "DSEU Wazirpur Campus-I",
        "eligibility": "XII Passed with min. 60%",
        "duration": "2 Years",
        "fee": "INR 25,000 per semester"
    },
    {
        "title": "UG Diploma in Food Production",
        "code": "201103",
        "campus": "DSEU Wazirpur-II Campus (SSE Wazirpur)",
        "eligibility": "XII Passed with min. 60%",
        "duration": "2 Years",
        "fee": "INR 25,000 per semester"
    },
    {
        "title": "UG Diploma in Light Vehicles",
        "code": "201103",
        "campus": "G.B. Pant DSEU Okhla I Campus",
        "eligibility": "XII Passed with min. 60%",
        "duration": "2 Years",
        "fee": "INR 25,000 per semester"
    },
    {
        "title": "UG Diploma in Heavy Vehicles",
        "code": "201103",
        "campus": "G.B. Pant DSEU Okhla I Campus",
        "eligibility": "XII Passed with min. 60%",
        "duration": "2 Years",
        "fee": "INR 25,000 per semester"
    },
    {
        "title": "UG Diploma in German Language",
        "code": "201103",
        "campus": "G.B. Pant DSEU Okhla I Campus",
        "eligibility": "XII Passed with min. 60%",
        "duration": "2 Years",
        "fee": "INR 25,000 per semester"
    },
    {
        "title": "UG Diploma in Japanese Language",
        "code": "201103",
        "campus": "DSEU Okhla-II Campus",
        "eligibility": "XII Passed with min. 60%",
        "duration": "2 Years",
        "fee": "INR 25,000 per semester"
    },
    {
        "title": "UG Diploma in French Language",
        "code": "201103",
        "campus": "DSEU Dwarka Campus",
        "eligibility": "XII Passed with min. 60%",
        "duration": "2 Years",
        "fee": "INR 25,000 per semester"
    },
    {
        "title": "UG Diploma in Computer System Operator",
        "code": "201103",
        "campus": "Meerabai DSEU Maharani Bagh Campus",
        "eligibility": "XII Passed with min. 60%",
        "duration": "2 Years",
        "fee": "INR 25,000 per semester"
    },
    {
        "title": "UG Diploma in Apparel Retail Management and Merchandising",
        "code": "201103",
        "campus": "DSEU Ranhola Campus",
        "eligibility": "XII Passed with min. 60%",
        "duration": "2 Years",
        "fee": "INR 25,000 per semester"
    },
    {
        "title": "Diploma in Pharmacy",
        "code": "201103",
        "campus": "Meerabai DSEU Maharani Bagh Campus",
        "eligibility": "XII Passed with min. 60%",
        "duration": "2 Years",
        "fee": "INR 25,000 per semester"
    }
]

export { diplomaPrograms, ugDiplomaPrograms };