export const eocData = {
    description:
    "The Equal Opportunity Cell (EOC) at Delhi Skill and Entrepreneurship University (DSEU) is committed to ensure that every individual—regardless of background, identity, or socio-economic status—has equal access to opportunities, resources, and services. The EOC strives to create a campus culture rooted in inclusivity, equity, and dignity.",
    objectives: [
      "Promote equality and inclusivity within the university",
      "Addressing discrimination",  
      "Awareness programs",
      "Support Systems",
      "Scholarships",
      "Liaison and Coordination",
      "Monitoring and Reporting",
    ],
    commitment:
      "The Equal Opportunity Cell is dedicated to empowering all students and creating a safe, fair, and supportive academic environment. By addressing structural barriers and encouraging diverse participation, the EOC plays a pivotal role in building a more just and equitable society within the university.",
    members: [
      {
        name: "Prof(Dr.) Arindam Kumar Chanda",
        role: "Director – EOC"
      },
      {
        name: "Prof(Dr.) Narender Jena",
        role: "Member"
      },
      {
        name: "Liaison Officer, DSEU",
        role: "Member"
      },
      {
        name: "Chairperson, ICC",
        role: "Member"
      },
      {
        name: "Coordinator, IQAC",
        role: "Member"
      },
      {
        name: "Ms. Sangeeta Jain",
        role: "Member"
      },
      {
        name: "Mr. Dhruv Kumar Yadav",
        role: "Member"
      },
      {
        name: "Ms. Parvathy Unnikrishnan",
        role: "Member Secretary"
      }
    ]
  };
  