export const eocData = {
  description:
    "The Equal Opportunity Cell (EOC) at Delhi Skill and Entrepreneurship University (DSEU) is dedicated to ensuring that every individual—irrespective of background, identity, or socio-economic status—has equitable access to opportunities, resources, and services. The EOC is committed to fostering a campus environment grounded in inclusivity, equity, and dignity for all members of the University community.",

  objectives: [
    "Promote equality and inclusion across the university.",
    "Prevent and address all forms of discrimination.",
    "Organize awareness and sensitization programs.",
    "Provide support systems for marginalized groups.",
    "Facilitate scholarships and financial aid.",
    "Coordinate with relevant internal and external bodies.",
    "Monitor policies and report on progress."
  ],
  commitment:
    "The Equal Opportunity Cell is dedicated to empowering all students and fostering a safe, fair, and supportive academic environment. By addressing structural barriers and promoting diverse participation, the EOC plays a vital role in advancing a more just and equitable society within the University.",

    members: [
    {
      name: "Prof(Dr.) Arindam Kumar Chanda",
      role: "Director – EOC"
    },
    {
      name: "Prof(Dr.) Narender Jena",
      role: "Member"
    },
    {
      name: "Liaison Officer, DSEU",
      role: "Member"
    },
    {
      name: "Chairperson, ICC",
      role: "Member"
    },
    {
      name: "Coordinator, IQAC",
      role: "Member"
    },
    {
      name: "Ms. Sangeeta Jain",
      role: "Member"
    },
    {
      name: "Mr. Dhruv Kumar Yadav",
      role: "Member"
    },
    {
      name: "Ms. Parvathy Unnikrishnan",
      role: "Member Secretary"
    }
  ]
};
