export const examinationSectionKeys = [
    { key: "exam datesheet", index: 0 },
    { key: "exam results", index: 1 },
    { key: "exam fee", index: 2 },
    { key: "exam notices", index: 3 },
];

export const examinationCards = [
    {
        title: "Datesheet",
        content: [],
        buttonText: "View All Datesheets",
        link: "/examination/datesheet"
    },
    {
        title: "Result",
        content: [],
        buttonText: "View Results",
        link: "/examination/results"
    },
    {
        title: "Fee Link",
        content: [],
        buttonText: "View Links",
        link: "/examination/fee-links"
    },
    {
        title: "Notices",
        content: [],
        buttonText: "View All Notices",
        link: "/examination/notices"
    },
];
