export const profileData = {
  "/BPIBS": {
    name: "Prof. Girish Kumar",
    designation: "Professor in Computer Applications (MCA)",
    education: [
      "Ph.D.( Applications of Graph Theory and Queueing Models in Distributed Operating System Architecture) awarded in 2005.",
      "MCA from Gurukul Kangri Vishwavidyalaya in 1996.",
      "M.Sc.( Physics ) from Gurukul Kangri Vishwavidyalaya in 1993.",

    ],
  },
  "/vivekvihar": {
    name: "Prof. Vivek Kumar",
    designation: "Associate Professor in Computer Science",
    education: [
      "Ph.D. in Computer Science and Engineering.",
      "M.Tech. from IIT Delhi.",
      "B.Tech. in Computer Science from DCE."
    ],
  },
  "/Mayurvihar": {
    name: "Prof. Ankit Agarwal",
    designation: "Assistant Professor in Information Technology",
    education: [
      "Ph.D. in Information Security.",
      "M.Tech. in Computer Science from BITS Pilani.",
      "B.Tech. in Information Technology from IGDTUW."
    ],
  },
  "/shakarpur2": {
    name: "Prof. Priya Gupta",
    designation: "Assistant Professor in Data Science",
    education: [
      "Ph.D. in Data Science and Machine Learning.",
      "M.Sc. in Data Analytics from JNU.",
      "B.Sc. in Computer Science from DU."
    ],
  },
};