export const iccData = {
  description: 
  "Delhi Skill and Entrepreneurship University (DSEU) is a coeducational institution dedicated to ensuring equal opportunities for all individuals. The University promotes a professional and respectful environment where men and women collaborate in harmony. The Internal Complaints Committee (ICC) is committed to raising awareness among students and staff, and to fostering a campus culture that actively prevents sexual harassment. All incidents of sexual harassment must be reported to the Committee, which undertakes appropriate disciplinary measures in accordance with the University's established rules and regulations.",

    objectives: [
      "Establish an environment in which women staff feel safe and supported to voice concerns without fear of retaliation.",
      "Cultivate a culture that does not tolerate harassment or discrimination in any form.",
      "Empower individuals to report inappropriate behavior with confidence and assurance of protection.",
      "Advance gender equality by addressing systemic challenges faced by women in academia.",
      "Eliminate gender bias and ensure equitable access to resources and opportunities.",
      "Promote the professional growth and advancement of women staff members.",
      "Ensure fairness and transparency throughout all complaint investigation processes.",
      "Provide comprehensive guidelines and conduct impartial, objective investigations.",
      "Treat all individuals involved in the process with respect, dignity, and sensitivity."
    ],

  members: [
    {
      name: "Prof(Dr.) Kamna Sachdeva",
      role: "Presiding Officer"
    },
    {
      name: "Ms. Mansi Gupta",
      role: "External Member"
    },
    {
      name: "Dr. Ashima Sharma",
      role: "Member"
    },
    {
      name: "Ms. Preeti Vajpeyi",
      role: "Member"
    },
    {
      name: "Ms. Parvathy Unnikrishnan",
      role: "Member"
    },
    {
      name: "Ms. Priya",
      role: "Member"
    },
    {
      name: "Mr. Nitesh Kumar",
      role: "Member"
    },
    {
      name: "Mr. Yudhveer Kumar Verma",
      role: "Member"
    },
    {
      name: "Mr. Nimit Kalra",
      role: "Member"
    }
  ]
}