export const iccData = {
  description:
    "Delhi Skill and Entrepreneurship University (DSEU) is a coeducational institution committed to providing equal opportunities to all. The University fosters a professional and respectful environment where men and women work together harmoniously. The Internal Complaints Committee (ICC) is dedicated to sensitizing students and staff, ensuring a campus culture that prevents sexual harassment. All complaints of sexual harassment are to be reported to the Committee, which takes appropriate disciplinary action in line with the University’s rules and regulations.",

  objectives: [
    "Create an environment where women staff feel safe and supported to raise concerns without fear of reprisal.",
    "Foster a culture where harassment and discrimination are not tolerated.",
    "Empower individuals to speak up against inappropriate behavior.",
    "Promote gender equality by addressing systemic issues affecting women in academia.",
    "Tackle gender bias and ensure equitable access to opportunities.",
    "Support the professional advancement of women.",
    "Uphold fairness and transparency in complaint investigations.",
    "Provide clear guidelines and conduct impartial investigations.",
    "Treat all parties involved with respect and dignity."
  ],

  members: [
    {
      name: "Prof(Dr.) Kamna Sachdeva",
      role: "Presiding Officer"
    },
    {
      name: "Ms. Mansi Gupta",
      role: "External Member"
    },
    {
      name: "Ms. Preeti Vajpeyi",
      role: "Member"
    },
    {
      name: "Ms. Parvathy Unnikrishnan",
      role: "Member"
    },
    {
      name: "Ms. Priya",
      role: "Member"
    },
    {
      name: "Mr. Nitesh Kumar",
      role: "Member"
    },
    {
      name: "Mr. Yudhveer Kumar Verma",
      role: "Member"
    },
    {
      name: "Mr. Nimit Kalra",
      role: "Member"
    }
  ]
}