const aboutTheUniversity = {
    info1: [
        "The Delhi Skill and Entrepreneurship University (DSEU) was established in August 2020 by the Government of NCT of Delhi to provide students with world-class skill education, enabling access to aspirational careers, fostering an entrepreneurial mindset, and promoting entrepreneurship. DSEU strives to create a win-win situation for both the youth and industry by addressing existing gaps in skill training.",
        "Drawing inspiration from the educational philosophies of thinkers like Mahatma Gandhi and Vinoba Bhave, DSEU seeks to integrate the hand, head, and heart for a balanced life and lifelong learning. The University emphasizes teaching both self-reliance for lifelong independence and the wisdom to nurture and value interdependence."
    ],

    objectives: [
        "To transform the current paradigm of skilling, making skill acquisition aspirational, and providing opportunities for skilling, up-skilling, and re-skilling for all.",
        "To support and nurture entrepreneurs and entrepreneurship."
    ],

    info2: [
        "The University offers courses to individuals from all walks of life, empowering marginalized and minority groups by providing access to world-class education. DSEU aims to develop aware, responsible, and well-rounded citizens.",
        "The course curriculum at DSEU is aligned with industry needs, preparing graduates to be career-ready. The University focuses on holistic development at affordable costs, ensuring that no student is denied admission due to financial constraints. DSEU also offers scholarships, freeships, financial assistance, and support through Delhi government schemes to help students pursue higher education."
    ]
}

export { aboutTheUniversity };
