const aboutTheUniversity = {
    info1: [
        "The Delhi Skill and Entrepreneurship University (DSEU) was established in August 2020 by the Government of NCT of Delhi to equip students with world-class skill education to enable access to aspirational jobs and inculcate entrepreneurial mindset and entrepreneurship. DSEU aims to create a win-win for the youth and the industry by filling the existing gaps in skill training.",
        "Building on the education philosophy of thinkers such as Mahatma Gandhi and Vinoba Bhave, DSEU aims to integrate the use of the hand, head, and heart for balanced living and engagement in lifelong learning. The focus will be on teaching both self-reliance for life-long independence and the wisdom towards nurturing and valuing interdependence.",
        "Building on the education philosophy of thinkers such as Mahatma Gandhi and Vinoba Bhave, DSEU aims to integrate the use of the hand, head, and heart for balanced living and engagement in lifelong learning. The focus will be on teaching both self-reliance for life-long independence and the wisdom towards nurturing and valuing interdependence.",
    ],

    objectives: [
        "To change the existing paradigm of skilling, make skill acquisition aspirational and provide an opportunity to all for skilling, up-skilling, and re-skilling.",
        "Support and nurture entrepreneurs and entrepreneurship"
    ],

    info2: [
        "The University will offer courses to people from all walks of life and empower the marginalized and minority groups by providing them with an opportunity to attain world-class education.  The University aims to develop aware and well-rounded citizens.",

        "The course curriculum offered at DSEU will be inspired by industry requirements and will help graduates to be career-ready. Holistic development at affordable costs will be the aim of the University while also ensuring that no student is denied admission due to lack of the ability to pay. The University will provide the opportunities of scholarships, freeships and financial assistance for getting loans and support from the Delhi government schemes for higher education."
    ]
}

export { aboutTheUniversity };