const Content = {
    id: 1,
    name: "Content",
    content: [
        "The DSEU Library is designed to support learning, research, and the development of reading habits. Each campus has its own library, and these spaces are being improved to better meet the needs of today’s students. While technology makes information easily accessible, it has also led to a decline in reading. DSEU’s libraries aim to offer a balanced environment with both digital and print resources to encourage focused learning."
    ],
};

const List = {
    id: 2,
    name: "list",
    content: [
        "Our library system spans a diverse range of spaces, from specialized collections to collaborative learning hubs.",

        "Each library is thoughtfully designed to support exploration, research, and academic growth.",

        "All libraries are integrated and provide learners and faculty unified access through KOHA Library Management System. To access, please click on the "
    ]
};




export { Content, List };  