const Content = {
    id: 1,
    name: "Content",
    content: [
        "DSEU Library is envisioned to be a shared space for learning, knowledge creation and research by nurturing the habit of reading. The libraries at each of the 15 campuses are being re-imagined and revamped to be a transformational space for a 21st century learner. While access to smartphones and smart devices has meant that learners can access information with the click of a button, it has also meant loss in reading habits. DSEU’s libraries are a rich store of digital and print resources."
    ],
};

const List = {
    id: 2,
    name: "list",
    content: [
        "We have 15 main and 3 mini libraries across the campuses.",

        "The libraries house 2,00,000 textbooks.",

        "16,000 reference books.",

        "All libraries are integrated and provide learners and faculty unified access through KOHA Library Management System. To access, please click on the "
    ]
};




export { Content, List };  