// this is placeholder/temporary data
export const informationBulletin = [
    {
        title: "Admissions 25-26",
        content: [
            "Students of State Universities of Delhi",
            "Financial Assistance to the students Under EWS Scheme",
            "ACM-USICT",
            "USS Placement Coordinators",
            "Alumni Portal",
            "NCC Cadet Enrolment Drive",
        ],
        buttonText: "Apply Online",
    },
    {
        title: "Students",
        content: [
            "Students of State Universities of Delhi",
            "Financial Assistance to the students Under EWS Scheme",
            "ACM-USICT",
            "USS Placement Coordinators",
            "Alumni Portal",
            "NCC Cadet Enrolment Drive",
        ],
        buttonText: "Online Fee Services",
    },
    {
        title: "Important Links",
        content: [
            "Students of State Universities of Delhi",
            "Financial Assistance to the students Under EWS Scheme",
            "ACM-USICT",
            "USS Placement Coordinators",
            "Alumni Portal",
            "NCC Cadet Enrolment Drive",
        ],
        buttonText: "Online Portal",
    },
    {
        title: "Alerts & Circulars",
        content: [
            "Students of State Universities of Delhi",
            "Financial Assistance to the students Under EWS Scheme",
            "ACM-USICT",
            "USS Placement Coordinators",
            "Alumni Portal",
            "NCC Cadet Enrolment Drive",
        ],
        buttonText: "View Notices",
    },
];
