export const pgPrograms = [
    {
        "title": "MBA International Business Management",
        "code": "C03",
        "campus": "DSEU PUSA-II Campus",
        "duration": "2 Years",
        "fee": "₹87,000 per semester"
    },
    {
        "title": "PG Diploma in Cyber Law (1 year program)",
        "code": "E01",
        "campus": "Ambedkar DSEU Shakarpur-I Campus",
        "duration": "1 Year",
        "fee": "₹25,000 per semester"
    },
    {
        "title": "MBA Entrepreneurship",
        "code": "E02",
        "campus": "Bhai Parmanand DSEU Shakarpur-II",
        "duration": "2 Years",
        "fee": "₹87,000 per semester"
    },
    {
        "title": "Master of Computer Application",
        "code": "E02",
        "campus": "Bhai Parmanand DSEU Shakarpur-II",
        "duration": "2 Years",
        "fee": "₹87,000 per semester"
    },
    {
        "title": "MBA Data Analytics",
        "code": "E02",
        "campus": "Bhai Parmanand DSEU Shakarpur-II",
        "duration": "2 Years",
        "fee": "₹87,000 per semester"
    },
    {
        "title": "MBA Retail Management",
        "code": "E04",
        "campus": "DSEU Vivek Vihar Campus",
        "duration": "2 Years",
        "fee": "₹87,000 per semester"
    },
    {
        "title": "MTech Tool Engineering",
        "code": "N05",
        "campus": "DSEU Wazirpur-I Campus",
        "duration": "2 Years",
        "fee": "₹87,000 per semester"
    },
    {
        "title": "PG Diploma in Precision Engineering (1 year program)",
        "code": "N05",
        "campus": "DSEU Wazirpur-I Campus",
        "duration": "1 Year",
        "fee": "₹50,000 per semester"
    },
    {
        "title": "MBA Finance",
        "code": "W02",
        "campus": "DSEU Dwarka Campus",
        "duration": "2 Years",
        "fee": "₹87,000 per semester"
    },
    {
        "title": "MBA Healthcare Facility Management",
        "code": "S01",
        "campus": "CHAMPS Okhla-II",
        "duration": "2 Years",
        "fee": "₹87,000 per semester"
    },
    {
        "title": "MTech Computer Science Engineering - AI & ML",
        "code": "S02",
        "campus": "DSEU Okhla-I Campus",
        "duration": "2 Years",
        "fee": "₹87,000 per semester"
    },
    {
        "title": "MTech Electronics & Communication Engineering - IoT",
        "code": "S02",
        "campus": "DSEU Okhla-I Campus",
        "duration": "2 Years",
        "fee": "₹87,000 per semester"
    },
    {
        "title": "MTech Mechanical Engineering",
        "code": "S02",
        "campus": "DSEU Okhla-I Campus",
        "duration": "2 Years",
        "fee": "₹87,000 per semester"
    },
    {
        "title": "MBA Management Information System",
        "code": "S03",
        "campus": "DSEU Okhla-II Campus",
        "duration": "2 Years",
        "fee": "₹87,000 per semester"
    },
    {
        "title": "B.Lib. (1 year program)",
        "code": "S04",
        "campus": "Meerabai DSEU Maharani Bagh Campus",
        "duration": "1 Year",
        "fee": "₹50,000 per semester"
    },
    {
        "title": "M.Sc Medical Laboratory Sciences",
        "code": "W02",
        "campus": "DSEU Dwarka Campus",
        "duration": "2 Years",
        "fee": "₹50,000 per semester"
    }
]

