// export const graphData = [
//     {
//         labels: ["Group A", "Group B", "Group C", "Group D"],
//         datasets: [
//             { label: "Girls", data: [10, 20, 20, 40], backgroundColor: "#1E3A8A" },
//             { label: "Boys", data: [20, 20, 25, 50], backgroundColor: "#F97316" },
//         ],
//     },
//     {
//         labels: ["Group A", "Group B", "Group C", "Group D"],
//         datasets: [
//             { label: "Girls", data: [15, 25, 18, 35], backgroundColor: "#1E3A8A" },
//             { label: "Boys", data: [22, 28, 30, 27], backgroundColor: "#F97316" },
//         ],
//     },
//     {
//         labels: ["Group A", "Group B", "Group C", "Group D"],
//         datasets: [
//             { label: "Girls", data: [12, 18, 22, 38], backgroundColor: "#1E3A8A" },
//             { label: "Boys", data: [25, 26, 28, 32], backgroundColor: "#F97316" },
//         ],
//     },
//     {
//         labels: ["Group A", "Group B", "Group C", "Group D"],
//         datasets: [
//             { label: "Girls", data: [20, 30, 25, 45], backgroundColor: "#1E3A8A" },
//             { label: "Boys", data: [18, 22, 27, 35], backgroundColor: "#F97316" },
//         ],
//     },
//     {
//         labels: ["Group A", "Group B", "Group C", "Group D"],
//         datasets: [
//             { label: "Girls", data: [14, 22, 28, 37], backgroundColor: "#1E3A8A" },
//             { label: "Boys", data: [21, 24, 29, 34], backgroundColor: "#F97316" },
//         ],
//     },
//     {
//         labels: ["Group A", "Group B", "Group C", "Group D"],
//         datasets: [
//             { label: "Girls", data: [18, 26, 32, 41], backgroundColor: "#1E3A8A" },
//             { label: "Boys", data: [23, 28, 31, 36], backgroundColor: "#F97316" },
//         ],
//     },
// ];

