export const REGISTRARINFO = {
  name: "Shri. Shailendra Singh Parihar,IAS",
  designation: "Registrar",
  university: "Delhi Skill and Entrepreneurship University (DSEU)",

  // profileOverview: `
  //   Prof. Dr. Gagan Dhawan completed his graduation and post-graduation at the University of Delhi, India. He received the Universitas 21 Fellowship for a Master’s in Bioinformatics at the University of Edinburgh, UK, and the UGC-Raman Award for postdoctoral research at the University of Massachusetts, Boston, USA. He is a Fellow of the Indian Chemical Society (FICS), Chartered Chemist (CChem), and Fellow of the Royal Society of Chemistry (FRSC), UK. Recognized for teaching excellence, he received the Meritorious Teacher Award (2014) and INSA Teachers Award (2020). He serves as a Council Member at the National Commission for Allied and Healthcare Professions (NCAHP), under the Ministry of Health and Family Welfare, Government of India. His research focuses on novel small-molecule inhibitors and natural polymer based smart self-assembled nanostructures for biomedical applications.
  // `,
  profileOverview: `
    Shri. Shailendra Singh Parihar,IAS
  `,

  message:
    "Education is more than knowledge; it's the ability to create change. DSEU empowers learners with the skills, confidence, and mindset to tackle challenges and shape a better society.",
};
