export const data = {
    introduction: [
        "Delhi Skill and Entrepreneurship University (DSEU) is committed to making quality education accessible to all. To support students from diverse backgrounds, the university facilitates a range of scholarships aimed at promoting academic excellence and reducing financial barriers. These scholarships are made available through government initiatives as well as collaborations with industry partners and philanthropic organizations."
    ],

    philosophy: [
        "DSEU aims to ensure that all meritorious students having secured admission in the Universityshall not be denied a seat due to financial constraints. DSEU hosts a number of institutional as wellas external scholarships, which the students can avail based on the eligibility criteria laid down by the University and other funding agencies respectively.The table below summarizes the available scholarships for DSEU students to support their academic journey. The detailed modalities of each of the scholarship opportunities is described in the next section."
    ],

    table:[
        {
            id: 1,
            name: "Merit-cum-Means linked Financial Assistance Scheme for Pursuing Higher Education in State Universities in Delhi (through e-district portal)"
          },
          {
            id: 2,
            name: "Merit-cum-Means Scholarship Scheme by DSEU"
          },
          {
            id: 3,
            name: "Stepping-stone scholarship"
          },
          {
            id: 4,
            name: "Topper’s scholarship"
          },
          {
            id: 5,
            name: "Raman Kant Munjal Scholarship 2021 (Selection Partner - iDreamCareer)"
          },
          {
            id: 6,
            name: "Mahindra All India Talent Scholarship (MAITS) by K.C Mahindra Education Trust"
          },
          {
            id: 7,
            name: "Surya Kiran Scholarship (By Sun Foundation)"
          },
          {
            id: 8,
            name: "Data Analytics Scholarship (By The IKIGAI Lab)"
          },
          {
            id: 9,
            name: "Vidyasaarathi Scholarship"
          },
          {
            id: 10,
            name: "Buddy4Study Scholarship Portal"
          },
          {
            id: 11,
            name: "Jai Krishna Scholarship"
          }
    ],
    details: [
        {
          content:
            "For detailed information about available scholarships and eligibility criteria. ",
          path:
             "/scholarship/Scholarship_DSEU.docx-2.pdf"
        }
]


}