import {
    agrimTomar,
    ahmadOmair,
    binduNair,
    chancellor,
    dipaloBansal,
    dnJena,
    drAmitKharapade,
    drGhanshyam,
    gagandhawan,
    girishKumar,
    janitVerma,
    kamnaSachdeva,
    kaushalSachdeva,
    kavitaKhanna,
    kieraatSrivastava,
    kkChandan,
    kmCleetus,
    makarandDevidasJoshi,
    manjuJain,
    monicaChopra,
    mukeshKumarGupta,
    niharikaPandey,
    omPrakashSingh,
    pankajLathar,
    pankarKumarSigh,
    panvirChitre,
    parvathyUnnikrishan,
    porusuRamananiah,
    pramodKumarGoyal,
    punitaDuhan,
    ravinderJohar,
    ravinderSingh,
    rkReddy,
    ruchikaSingh,
    sampuranandaMishra,
    sangeetaJain,
    sanjayDahiya,
    shrutiTripathi,
    surrendarKumarSharma,
    svVageesha,
    veenaUpadhay,
    vibhakarShrimali,
    vicechancellor,
  } from '../assets/team-dseu'
  
  const members = [
    {
      id: 1,
      name: "Sh. Vinai Kumar Saxena",
      src: chancellor,
      designation: "Hon'ble Chancellor & Lt. Governor"
    },
    {
      id: 2,
      name: "Prof. (Dr.) Ashok Kumar Nagawat",
      src: vicechancellor,
      designation: "Vice-Chancellor"
    },
    {
      id: 3,
      name: "Prof. (Dr.) Gagan Dhawan",
      src: gagandhawan,
      designation: "Registrar, Dean - Allied Medical Sciences, Dean - International Affairs"
    },
    {
      id: 4,
      name: "Prof. (Dr.) Girish Kumar Sharma",
      src: girishKumar,
      designation: "Dean (Research)"
    },
    {
      id: 5,
      name: "Col. Sanjay Dahiya",
      src: sanjayDahiya,
      designation: "Controller of Finance"
    },
    {
      id: 6,
      name: "Dr. Pankaj Lathar",
      src: pankajLathar,
      designation: "Controller of Examination"
    },
    {
      id: 7,
      name: "Pravir Chitre",
      src: panvirChitre,
      designation: "Joint Director (IT)"
    },
    {
      id: 8,
      name: "Bindu Nair",
      src: binduNair,
      designation: "Deputy Registrar (Human Resources)"
    },
    {
      id: 9,
      name: "K.M. Cleetus",
      src: kmCleetus,
      designation: "Deputy Controller of Accounts"
    },
    {
      id: 10,
      name: "Prof. (Dr.) Kamna Sachdeva",
      src: kamnaSachdeva,
      designation: "Joint Director (Academics), DSEU, HQs"
    },
    {
      id: 11,
      name: "Ms. Sangeeta Jain",
      src: sangeetaJain,
      designation: "Campus Director - DSEU Siri Fort Campus"
    },
    {
      id: 12,
      name: "Prof. Dr. N. Jena",
      src: dnJena,
      designation: "Campus Director (DSEU PUSA-II CAMPUS)"
    },
    {
      id: 13,
      name: "Dr. Pramod Kumar Goyal",
      src: pramodKumarGoyal,
      designation: "Campus Director - Ranhola Campus"
    },
    {
      id: 14,
      name: "Prof. Vibhakar Shrimali",
      src: vibhakarShrimali,
      designation: "Campus Director - G.B Pant DSEU Okhla III & Okhla I"
    },
    {
      id: 15,
      name: "Prof. (Dr.) Shruti Tripathi",
      src: shrutiTripathi,
      designation: "Campus Director - Kasturba DSEU Pitampura Campus"
    },
    {
      id: 16,
      name: "Dr. Ghanshyam",
      src: drGhanshyam,
      designation: "Campus Director - Ambedkar DSEU Shakarpur - I Campus"
    },
    {
      id: 17,
      name: "Dr. Pankaj Kumar Singh",
      src: pankarKumarSigh,
      designation: "Campus Director - DSEU Wazirpur - I Campus"
    },
    {
      id: 18,
      name: "Dr. Sampurnananda Mishra",
      src: sampuranandaMishra,
      designation: "Campus Head - Dr. H.J. Bhabha DSEU Mayur Vihar Campus"
    },
    {
      id: 19,
      name: "Mr. Porusu Ramanaiah",
      src: porusuRamananiah,
      designation: "Campus Director - DSEU Rajokri Campus"
    },
    {
      id: 20,
      name: "Mr. Ravinder Singh",
      src: ravinderSingh,
      designation: "Campus Director - Guru Nanak Dev DSEU Rohini Campus"
    },
    {
      id: 21,
      name: "Prof. (Dr.) Girish Kumar Sharma",
      src: girishKumar,
      designation: "Campus Director - Bhai Parmanand DSEU Shakarpur Campus - II & Dean (Research)"
    },
    {
      id: 22,
      name: "Dr. Punita Duhan",
      src: punitaDuhan,
      designation: "Campus Director - DSEU Vivek Vihar Campus"
    },
    {
      id: 23,
      name: "Ms. Manju Jain",
      src: manjuJain,
      designation: "Campus Director - Meerabai DSEU Maharani Bagh Campus"
    },
    {
      id: 24,
      name: "Dr. Kavita Khanna",
      src: kavitaKhanna,
      designation: "Campus Director - DSEU Dwarka Campus"
    },
    {
      id: 25,
      name: "Dr. Monica Chopra",
      src: monicaChopra,
      designation: "Campus Director - DSEU Dheerpur Campus"
    },
    {
      id: 26,
      name: "Dr. S V Vageesha",
      src: svVageesha,
      designation: "Campus Director - Aryabhatt DSEU Ashok Vihar Campus"
    },
    {
      id: 27,
      name: "Prof. Dipali Bansal",
      src: dipaloBansal,
      designation: "Campus Director - DSEU Champs Okhla-II Campus"
    },
    {
      id: 28,
      name: "Dr. Om Prakash Singh",
      src: omPrakashSingh,
      designation: "Campus Director - DSEU Pusa Campus I"
    },
    {
      id: 29,
      name: "K K Chandan",
      src: kkChandan,
      designation: "OSD (Recruitment)"
    },
    {
      id: 30,
      name: "Mukesh Kumar Gupta",
      src: mukeshKumarGupta,
      designation: "OSD (Legal/RTI)"
    },
    {
      id: 31,
      name: "Makarand Devidas Joshi",
      src: makarandDevidasJoshi,
      designation: "OSD (Purchase)"
    },
    {
      id: 32,
      name: "Dr. Amit Kharpade",
      src: drAmitKharapade,
      designation: "Liaison officer (SC/ST/PwD)"
    },
    {
      id: 33,
      name: "Parvathy Unnikrishnan",
      src: parvathyUnnikrishan,
      designation: "Assistant Registrar"
    },
    {
      id: 34,
      name: "Dr. Surender Kumar Sharma",
      src: surrendarKumarSharma,
      designation: "Assistant Registrar (Store and Purchase)"
    },
    {
      id: 35,
      name: "Dr. Ruchika Singh",
      src: ruchikaSingh,
      designation: "Assistant Registrar (Exams and Admission)"
    },
    {
      id: 36,
      name: "R.K. Reddy",
      src: rkReddy,
      designation: "Senior Accounts Officer"
    },
    {
      id: 37,
      name: "Veena Upadhyay",
      src: veenaUpadhay,
      designation: "Accounts Officer"
    },
    {
      id: 38,
      name: "Kireet Kant Srivastava",
      src: kieraatSrivastava,
      designation: "Executive Engineer (Civil)"
    },
    {
      id: 39,
      name: "Jatin Verma",
      src: janitVerma,
      designation: "PIO-RTI & In-Charge PGMS/CPGRAMS/LGLP"
    },
    {
      id: 40,
      name: "Ahmad Omair",
      src: ahmadOmair,
      designation: "Placement and Partnership Manager"
    },
    {
      id: 41,
      name: "Niharika Pandey",
      src: niharikaPandey,
      designation: "Placement and Partnership Manager"
    },
    {
      id: 42,
      name: "Kaushalender Varma",
      src: kaushalSachdeva,
      designation: "Placement and Partnership Manager"
    },
    {
      id: 43,
      name: "Dr. Ravinder Jhorar",
      src: ravinderJohar,
      designation: "Placement and Partnership Manager"
    },
    {
      id: 44,
      name: "Agrim Tomar",
      src: agrimTomar,
      designation: "Placement and Partnership Manager"
    },
    {
      id: 45,
      name: "Dr Dipti Mal",
      src: "", // No match found
      designation: "Placement and Partnership Manager"
    },
    {
      id: 46,
      name: "Mr Amreek Singh",
      src: "", // No match found
      designation: "Placement and Partnership Manager"
    }
  ];
  