import {
  agrimTomar,
  ahmadOmair,
  binduNair,
  chancellor,
  dipaloBansal,
  dnJena,
  drAmitKharapade,
  drGhanshyam,
  gagandhawan,
  girishKumar,
  janitVerma,
  kamnaSachdeva,
  kaushalSachdeva,
  kavitaKhanna,
  kieraatSrivastava,
  kkChandan,
  kmCleetus,
  makarandDevidasJoshi,
  manjuJain,
  monicaChopra,
  mukeshKumarGupta,
  niharikaPandey,
  omPrakashSingh,
  pankajLathar,
  pankarKumarSigh,
  panvirChitre,
  parvathyUnnikrishan,
  porusuRamananiah,
  pramodKumarGoyal,
  punitaDuhan,
  ravinderJohar,
  ravinderSingh,
  rkReddy,
  ruchikaSingh,
  sampuranandaMishra,
  sangeetaJain,
  sanjayDahiya,
  shrutiTripathi,
  surrendarKumarSharma,
  svVageesha,
  veenaUpadhay,
  vibhakarShrimali,
  vicechancellor,
} from '../assets/team-dseu'

export const members = [
  {
    id: 1,
    name: "Sh. Vinai Kumar Saxena",
    src: chancellor,
    designation: "Hon'ble Chancellor & Lt. Governor",
    category: "Chancellor"
  },
  {
    id: 2,
    name: "Prof. (Dr.) Ashok Kumar Nagawat",
    src: vicechancellor,
    designation: "Vice-Chancellor",
    category: "Vice Chancellor"
  },
  {
    id: 3,
    name: "Prof. (Dr.) Gagan Dhawan",
    src: gagandhawan,
    designation: "Registrar, Dean - Allied Medical Sciences, Dean - International Affairs",
    category: "University Officers"
  },
  {
    id: 4,
    name: "Prof. (Dr.) Girish Kumar Sharma",
    src: girishKumar,
    designation: "Dean (Research)",
    category: "University Officers"
  },
  {
    id: 5,
    name: "Col. Sanjay Dahiya",
    src: sanjayDahiya,
    designation: "Controller of Finance",
    category: "University Officers"
  },
  {
    id: 6,
    name: "Dr. Pankaj Lathar",
    src: pankajLathar,
    designation: "Controller of Examination",
    category: "University Officers"
  },
  {
    id: 7,
    name: "Pravir Chitre",
    src: panvirChitre,
    designation: "Joint Director (IT)",
    category: "University Officers"
  },
  {
    id: 8,
    name: "Bindu Nair",
    src: binduNair,
    designation: "Deputy Registrar (Human Resources)",
    category: "University Officers"
  },
  {
    id: 9,
    name: "K.M. Cleetus",
    src: kmCleetus,
    designation: "Deputy Controller of Accounts",
    category: "University Officers"
  },
  {
    id: 10,
    name: "Prof. (Dr.) Kamna Sachdeva",
    src: kamnaSachdeva,
    designation: "Joint Director (Academics), DSEU, HQs",
    category: "University Officers"
  },
  {
    id: 11,
    name: "Ms. Sangeeta Jain",
    src: sangeetaJain,
    designation: "Campus Director - DSEU Siri Fort Campus",
    category: "Campus Directors"
  },
  {
    id: 12,
    name: "Prof. Dr. N. Jena",
    src: dnJena,
    designation: "Campus Director (DSEU PUSA-II CAMPUS)",
    category: "Campus Directors"
  },
  {
    id: 13,
    name: "Dr. Pramod Kumar Goyal",
    src: pramodKumarGoyal,
    designation: "Campus Director - Ranhola Campus",
    category: "Campus Directors"
  },
  {
    id: 14,
    name: "Prof. Vibhakar Shrimali",
    src: vibhakarShrimali,
    designation: "Campus Director - G.B Pant DSEU Okhla III & Okhla I",
    category: "Campus Directors"
  },
  {
    id: 15,
    name: "Prof. (Dr.) Shruti Tripathi",
    src: shrutiTripathi,
    designation: "Campus Director - Kasturba DSEU Pitampura Campus",
    category: "Campus Directors"
  },
  {
    id: 16,
    name: "Dr. Ghanshyam",
    src: drGhanshyam,
    designation: "Campus Director - Ambedkar DSEU Shakarpur - I Campus",
    category: "Campus Directors"
  },
  {
    id: 17,
    name: "Dr. Pankaj Kumar Singh",
    src: pankarKumarSigh,
    designation: "Campus Director - DSEU Wazirpur - I Campus",
    category: "Campus Directors"
  },
  {
    id: 18,
    name: "Dr. Sampurnananda Mishra",
    src: sampuranandaMishra,
    designation: "Campus Head - Dr. H.J. Bhabha DSEU Mayur Vihar Campus",
    category: "Campus Directors"
  },
  {
    id: 19,
    name: "Mr. Porusu Ramanaiah",
    src: porusuRamananiah,
    designation: "Campus Director - DSEU Rajokri Campus",
    category: "Campus Directors"
  },
  {
    id: 20,
    name: "Mr. Ravinder Singh",
    src: ravinderSingh,
    designation: "Campus Director - Guru Nanak Dev DSEU Rohini Campus",
    category: "Campus Directors"
  },
  {
    id: 21,
    name: "Prof. (Dr.) Girish Kumar Sharma",
    src: girishKumar,
    designation: "Campus Director - Bhai Parmanand DSEU Shakarpur Campus - II & Dean (Research)",
    category: "Campus Directors"
  },
  {
    id: 22,
    name: "Dr. Punita Duhan",
    src: punitaDuhan,
    designation: "Campus Director - DSEU Vivek Vihar Campus",
    category: "Campus Directors"
  },
  {
    id: 23,
    name: "Ms. Manju Jain",
    src: manjuJain,
    designation: "Campus Director - Meerabai DSEU Maharani Bagh Campus",
    category: "Campus Directors"
  },
  {
    id: 24,
    name: "Dr. Kavita Khanna",
    src: kavitaKhanna,
    designation: "Campus Director - DSEU Dwarka Campus",
    category: "Campus Directors"
  },
  {
    id: 25,
    name: "Dr. Monica Chopra",
    src: monicaChopra,
    designation: "Campus Director - DSEU Dheerpur Campus",
    category: "Campus Directors"
  },
  {
    id: 26,
    name: "Dr. S V Vageesha",
    src: svVageesha,
    designation: "Campus Director - Aryabhatt DSEU Ashok Vihar Campus",
    category: "Campus Directors"
  },
  {
    id: 27,
    name: "Prof. Dipali Bansal",
    src: dipaloBansal,
    designation: "Campus Director - DSEU Champs Okhla-II Campus",
    category: "Campus Directors"
  },
  {
    id: 28,
    name: "Dr. Om Prakash Singh",
    src: omPrakashSingh,
    designation: "Campus Director - DSEU Pusa Campus I",
    category: "Campus Directors"
  },
  {
    id: 29,
    name: "K K Chandan",
    src: kkChandan,
    designation: "OSD (Recruitment)",
    category: "Officers"
  },
  {
    id: 30,
    name: "Mukesh Kumar Gupta",
    src: mukeshKumarGupta,
    designation: "OSD (Legal/RTI)",
    category: "Officers"
  },
  {
    id: 31,
    name: "Makarand Devidas Joshi",
    src: makarandDevidasJoshi,
    designation: "OSD (Purchase)",
    category: "Officers"
  },
  {
    id: 32,
    name: "Dr. Amit Kharpade",
    src: drAmitKharapade,
    designation: "Liaison officer (SC/ST/PwD)",
    category: "Officers"
  },
  {
    id: 33,
    name: "Parvathy Unnikrishnan",
    src: parvathyUnnikrishan,
    designation: "Assistant Registrar",
    category: "Officers"
  },
  {
    id: 34,
    name: "Dr. Surender Kumar Sharma",
    src: surrendarKumarSharma,
    designation: "Assistant Registrar (Store and Purchase)",
    category: "Officers"
  },
  {
    id: 35,
    name: "Dr. Ruchika Singh",
    src: ruchikaSingh,
    designation: "Assistant Registrar (Exams and Admission)",
    category: "Officers"
  },
  {
    id: 36,
    name: "R.K. Reddy",
    src: rkReddy,
    designation: "Senior Accounts Officer",
    category: "Officers"
  },
  {
    id: 37,
    name: "Veena Upadhyay",
    src: veenaUpadhay,
    designation: "Accounts Officer",
    category: "Officers"
  },
  {
    id: 38,
    name: "Kireet Kant Srivastava",
    src: kieraatSrivastava,
    designation: "Executive Engineer (Civil)",
    category: "Officers"
  },
  {
    id: 39,
    name: "Jatin Verma",
    src: janitVerma,
    designation: "PIO-RTI & In-Charge PGMS/CPGRAMS/LGLP",
    category: "Officers"
  },
  {
    id: 40,
    name: "Ahmad Omair",
    src: ahmadOmair,
    designation: "Placement and Partnership Manager",
    category: "Training and Placement Officers"
  },
  {
    id: 41,
    name: "Niharika Pandey",
    src: niharikaPandey,
    designation: "Placement and Partnership Manager",
    category: "Training and Placement Officers"
  },
  {
    id: 42,
    name: "Kaushalender Varma",
    src: kaushalSachdeva,
    designation: "Placement and Partnership Manager",
    category: "Training and Placement Officers"
  },
  {
    id: 43,
    name: "Dr. Ravinder Jhorar",
    src: ravinderJohar,
    designation: "Placement and Partnership Manager",
    category: "Training and Placement Officers"
  },
  {
    id: 44,
    name: "Agrim Tomar",
    src: agrimTomar,
    designation: "Placement and Partnership Manager",
    category: "Training and Placement Officers"
  },
  {
    id: 45,
    name: "Dr Dipti Mal",
    src: "",
    designation: "Placement and Partnership Manager",
    category: "Training and Placement Officers"
  },
  {
    id: 46,
    name: "Mr Amreek Singh",
    src: "",
    designation: "Placement and Partnership Manager",
    category: "Training and Placement Officers"
  }
];