[
    {
      "id": 1,
      "name": "Sh. Vinai Kumar Saxena",
      "src": "",
      "designation": "Hon'ble Chancellor & Lt. Governor"
    },
    {
      "id": 2,
      "name": "Prof. (Dr.) Ashok Kumar Nagawat",
      "src": "",
      "designation": "Vice-Chancellor"
    },
    {
      "id": 3,
      "name": "Prof. (Dr.) Gagan Dhawan",
      "src": "",
      "designation": "Registrar, Dean - Allied Medical Sciences, Dean - International Affairs"
    },
    {
      "id": 4,
      "name": "Prof. (Dr.) Girish Kumar Sharma",
      "src": "",
      "designation": "Dean (Research)"
    },
    {
      "id": 5,
      "name": "Col. Sanjay Dahiya",
      "src": "",
      "designation": "Controller of Finance"
    },
    {
      "id": 6,
      "name": "Dr. Pankaj Lathar",
      "src": "",
      "designation": "Controller of Examination"
    },
    {
      "id": 7,
      "name": "Pravir Chitre",
      "src": "",
      "designation": "Joint Director (IT)"
    },
    {
      "id": 8,
      "name": "Bindu Nair",
      "src": "",
      "designation": "Deputy Registrar (Human Resources)"
    },
    {
      "id": 9,
      "name": "K.M. Cleetus",
      "src": "",
      "designation": "Deputy Controller of Accounts"
    },
    {
      "id": 10,
      "name": "Prof. (Dr.) Kamna Sachdeva",
      "src": "",
      "designation": "Joint Director (Academics), DSEU, HQs"
    },
    {
      "id": 11,
      "name": "Ms. Sangeeta Jain",
      "src": "",
      "designation": "Campus Director - DSEU Siri Fort Campus"
    },
    {
      "id": 12,
      "name": "Prof. Dr. N. Jena",
      "src": "",
      "designation": "Campus Director (DSEU PUSA-II CAMPUS)"
    },
    {
      "id": 13,
      "name": "Dr. Pramod Kumar Goyal",
      "src": "",
      "designation": "Campus Director - Ranhola Campus"
    },
    {
      "id": 14,
      "name": "Prof. Vibhakar Shrimali",
      "src": "",
      "designation": "Campus Director - G.B Pant DSEU Okhla III & Okhla I"
    },
    {
      "id": 15,
      "name": "Prof. (Dr.) Shruti Tripathi",
      "src": "",
      "designation": "Campus Director - Kasturba DSEU Pitampura Campus"
    },
    {
      "id": 16,
      "name": "Dr. Ghanshyam",
      "src": "",
      "designation": "Campus Director - Ambedkar DSEU Shakarpur - I Campus"
    },
    {
      "id": 17,
      "name": "Dr. Pankaj Kumar Singh",
      "src": "",
      "designation": "Campus Director - DSEU Wazirpur - I Campus"
    },
    {
      "id": 18,
      "name": "Dr. Sampurnananda Mishra",
      "src": "",
      "designation": "Campus Head - Dr. H.J. Bhabha DSEU Mayur Vihar Campus"
    },
    {
      "id": 19,
      "name": "Mr. Porusu Ramanaiah",
      "src": "",
      "designation": "Campus Director - DSEU Rajokri Campus"
    },
    {
      "id": 20,
      "name": "Mr. Ravinder Singh",
      "src": "",
      "designation": "Campus Director - Guru Nanak Dev DSEU Rohini Campus"
    },
    {
      "id": 21,
      "name": "Prof. (Dr.) Girish Kumar Sharma",
      "src": "",
      "designation": "Campus Director - Bhai Parmanand DSEU Shakarpur Campus - II & Dean (Research)"
    },
    {
      "id": 22,
      "name": "Dr. Punita Duhan",
      "src": "",
      "designation": "Campus Director - DSEU Vivek Vihar Campus"
    },
    {
      "id": 23,
      "name": "Ms. Manju Jain",
      "src": "",
      "designation": "Campus Director - Meerabai DSEU Maharani Bagh Campus"
    },
    {
      "id": 24,
      "name": "Dr. Kavita Khanna",
      "src": "",
      "designation": "Campus Director - DSEU Dwarka Campus"
    },
    {
      "id": 25,
      "name": "Dr. Monica Chopra",
      "src": "",
      "designation": "Campus Director - DSEU Dheerpur Campus"
    },
    {
      "id": 26,
      "name": "Dr. S V Vageesha",
      "src": "",
      "designation": "Campus Director - Aryabhatt DSEU Ashok Vihar Campus"
    },
    {
      "id": 27,
      "name": "Prof. Dipali Bansal",
      "src": "",
      "designation": "Campus Director - DSEU Champs Okhla-II Campus"
    },
    {
      "id": 28,
      "name": "Dr. Om Prakash Singh",
      "src": "",
      "designation": "Campus Director - DSEU Pusa Campus I"
    },
    {
      "id": 29,
      "name": "K K Chandan",
      "src": "",
      "designation": "OSD (Recruitment)"
    },
    {
      "id": 30,
      "name": "Mukesh Kumar Gupta",
      "src": "",
      "designation": "OSD (Legal/RTI)"
    },
    {
      "id": 31,
      "name": "Makarand Devidas Joshi",
      "src": "",
      "designation": "OSD (Purchase)"
    },
    {
      "id": 32,
      "name": "Dr. Amit Kharpade",
      "src": "",
      "designation": "Liaison officer (SC/ST/PwD)"
    },
    {
      "id": 33,
      "name": "Parvathy Unnikrishnan",
      "src": "",
      "designation": "Assistant Registrar"
    },
    {
      "id": 34,
      "name": "Dr. Surender Kumar Sharma",
      "src": "",
      "designation": "Assistant Registrar (Store and Purchase)"
    },
    {
      "id": 35,
      "name": "Dr. Ruchika Singh",
      "src": "",
      "designation": "Assistant Registrar (Exams and Admission)"
    },
    {
      "id": 36,
      "name": "R.K. Reddy",
      "src": "",
      "designation": "Senior Accounts Officer"
    },
    {
      "id": 37,
      "name": "Veena Upadhyay",
      "src": "",
      "designation": "Accounts Officer"
    },
    {
      "id": 38,
      "name": "Kireet Kant Srivastava",
      "src": "",
      "designation": "Executive Engineer (Civil)"
    },
    {
      "id": 39,
      "name": "Jatin Verma",
      "src": "",
      "designation": "PIO-RTI & In-Charge PGMS/CPGRAMS/LGLP"
    },
    {
      "id": 40,
      "name": "Ahmad Omair",
      "src": "",
      "designation": "Placement and Partnership Manager"
    },
    {
      "id": 41,
      "name": "Niharika Pandey",
      "src": "",
      "designation": "Placement and Partnership Manager"
    },
    {
      "id": 42,
      "name": "Kaushalender Varma",
      "src": "",
      "designation": "Placement and Partnership Manager"
    },
    {
      "id": 43,
      "name": "Dr. Ravinder Jhorar",
      "src": "",
      "designation": "Placement and Partnership Manager"
    },
    {
      "id": 44,
      "name": "Agrim Tomar",
      "src": "",
      "designation": "Placement and Partnership Manager"
    },
    {
      "id": 45,
      "name": "Dr Dipti Mal",
      "src": "",
      "designation": "Placement and Partnership Manager"
    },
    {
      "id": 46,
      "name": "Mr Amreek Singh",
      "src": "",
      "designation": "Placement and Partnership Manager"
    }
  ]
  