// export const ugPrograms = [
//     {
//         title: "B.S. Automotive Retail Management",
//         code: "114500",
//         campus: "BPIBS DSEU Campus-II",
//         duration: "4 Years",
//         fee: "25000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.S. Banking, Financial Services and Insurance",
//         code: "114501",
//         fee: "50000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.S. E-Commerce Operations and Digital Application",
//         code: "114502",
//         fee: "25000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.S. Retail Management",
//         code: "114503",
//         fee: "25000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.S. Supply Chain Management",
//         code: "114504",
//         fee: "25000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.S. Hospitality Management",
//         code: "114505",
//         fee: "87000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.S. Community Organisation and Development Practice",
//         code: "114506",
//         fee: "25000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.S. Digital Marketing and Data Analytics",
//         code: "114507",
//         fee: "50000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.S. Computer Applications",
//         code: "114508",
//         fee: "50000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.A. (Hons.) Spanish",
//         code: "114509",
//         fee: "25000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.S. Beauty Therapy",
//         code: "114510",
//         fee: "25000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.Sc. (Hons.) Mathematics",
//         code: "114511",
//         fee: "25000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.S. Office Management",
//         code: "114512",
//         fee: "25000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.A. (Hons) Fine Arts",
//         code: "114513",
//         fee: "25000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.S. Digital Media Design",
//         code: "114514",
//         fee: "50000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.S. Business Process Management",
//         code: "114515",
//         fee: "25000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.S. Fashion Design",
//         code: "114516",
//         fee: "25000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.S. Interior Design",
//         code: "114517",
//         fee: "25000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.S. Hospital Facility Management",
//         code: "114518",
//         fee: "50000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.S. Optometry",
//         code: "114519",
//         fee: "50000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.S. Entrepreneurship",
//         code: "114520",
//         fee: "50000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.S. Dialysis Technology",
//         code: "114521",
//         fee: "87000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.S. Emergency Medical Technology",
//         code: "114522",
//         fee: "87000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.S. Medical Laboratory Sciences",
//         code: "114523",
//         fee: "50000 Tuition Fees per Semester",
//     },
//     {
//         title: "B.S. Facility Management",
//         code: "114524",
//         fee: "50000 Tuition Fees per Semester",
//     },
// ];