const vision = {
    id: 1,
    name: "Vision",
    content: [
        "To set the standards for skilling and entrepreneurship education.",
        "To lead students at DSEU through a journey of personal transformation, empowering them to become agents of change in their communities.",
        "To become a leading partner in the sustainable growth of the industry and the country.",
    ],
};

const mission = {
    id: 2,
    name: "Mission",
    content: [
        "To accord dignity to all skills by emphasizing their teaching and learning.",

        "To inculcate an entrepreneurial mindset for sustainable growth of the planet, the country, the society, the industry and the individual.",

        "To work in partnership with the industry to nurture talent which is honed to be ready-to-work on the day of graduation.",
    ]
};


const keyPrincipals = {
    id: 3,
    name: "Key Principles",
    desc: "Delhi Skill and Entrepreneurship University has defined some key principles which are embedded in all its programs to help in the holistic development of all students:",
    content: [
        "Develop market-linked programs by customizing them to specific job roles.",
        "Multiple entry/exit options and offer integrated career pathways.",
        "Design inclusive programs.",
        "Ensure holistic development by deeply integrating employability/life skills in the curriculum.",
        "Leverage technology.",
        "Equip students with an entrepreneurial mindset."
    ]
};

export { vision, mission, keyPrincipals };