export const searchItems = [
    { name: "Home", path: "/" },
    { name: "About the University", path: "/about-us/About-the-University" },
    { name: "Vision and Mission", path: "/about-us/Vision-and-Mission" },
    { name: "History of DSEU", path: "/about-us/history" },
    { name: "Annual Report", path: "/about-us/annualReport" },
    { name: "Faculties & Department", path: "/academics/faculty" },
    { name: "Academic Administration", path: "/academics/academicAdministration" },
    { name: "Academic Regulations", path: "/academics/regulations" },
    { name: "Academic Calendar", path: "/academics/academic-calendar" },
    { name: "Academic Collaboration", path: "/academics/collaboration" },
    { name: "Internal Quality Assurance Cell (IQAC)", path: "/academics/IQAC" },
    { name: "Library", path: "/amenities/Library" },
    { name: "Central Zone Campuses", path: "/campus/zone/central zone" },
    { name: "North Zone Campuses", path: "/campus/zone/north zone" },
    { name: "South Zone Campuses", path: "/campus/zone/south zone" },
    { name: "East Zone Campuses", path: "/campus/zone/east zone" },
    { name: "West Zone Campuses", path: "/campus/zone/west zone" },
    { name: "Process and guidelines", path: "/admission/process-and-guidelines" },
    { name: "Fee Refund Policy", path: "/admission/refund-policy" },
    { name: "Administrative Offices", path: "/administration/administrative" },
    { name: "Chancellor", path: "/administration/chancellor" },
    { name: "Vice Chancellor", path: "/administration/vice-chancellor" },
    { name: "Registrar", path: "/registrar" },
    { name: "Recruitment Rules", path: "/administration/recruitment-rules" },
    { name: "NCC/NSS", path: "/ncc" },
    { name: "Sports", path: "/amenities/Sports" },
    { name: "Scholarship", path: "/amenities/Scholarship" },
    { name: "Internal Complaint Committee", path: "/amenities/ICC" },
    { name: "Anti-Ragging Cell", path: "amenities/Anti-Ragging" },
    { name: "Equal Oppurtunity Cell", path: "/amenities/Equal-Opportunity" },
    { name: "T & P Cell", path: "/placement" },
    { name: "Work with us", path: "/recruitment" },
    { name: "Entrepreneurship", path: "/Entrepreneurship" },
    { name: "Programs", path: "/courses" },
    { name: "UG Programs", path: "/courses/ug" },
    { name: "Undergraduate Programs", path: "/courses/ug" },
    { name: "PG Programs", path: "/courses/pg" },
    { name: "Postgraduate Programs", path: "/courses/pg" },
    { name: "Diploma Programs", path: "/courses/diploma" },
    { name: "Ambedkar DSEU Campus", path: "/campus/ambedkar dseu campus" },
    { name: "DSEU Ranhola Campus", path: "campus/dseu ranhola campus" },
    { name: "Bhai Parmanand DSEU Campus", path: "campus/Bhai Parmanand DSEU Campus" },
    { name: "DSEU Vivek Vihar Campus", path: "campus/DSEU Vivek Vihar Campus" },
    { name: "Guru Nanak Dev DSEU Campus", path: "campus/Guru Nanak Dev DSEU Campus" },
    { name: "Meerabai DSEU Campus", path: "campus/Meerabai DSEU Campus" },
    { name: "DSEU Mayur Vihar Campus", path: "campus/DSEU Mayur Vihar Campus" },
    { name: "DSEU Dwarka Campus", path: "campus/DSEU Dwarka Campus" },
    { name: "Board of Management", path: "/administration/administrative/board-of-management" },
    { name: "Statutory Bodies", path: "/administration/administrative/statutory-bodies" },
    { name: "Team DSEU", path: "/administration/administrative/team-dseu" },
    { name: "Statutes, University Act, Ordinances", path: "/administration/administrative/Statutes" },
    { name: "Statutory Committees", path: "/administration/administrative/advisory-board" },
    { name: "Employee Policies", path: "/administration/administrative/employee-policy" },
    { name: "Important Forms", path: "/administration/administrative/important-forms" },
    { name: "Office Orders", path: "/administration/administrative/office-orders" },
    { name: "Circulars", path: "/administration/administrative/circulars" },
    { name: "Tenders", path: "/tenders" },
    { name: "Grievance Form", path: "/grievance-form" },
    { name: "RTI", path: "/grievance-form" },
    { name: "Training and Placement Cell", path: "/placement" },
];
