export const QUERY_KEYS = Object.freeze({
    GET_DEPARTMENTS: "getDepartments",
    GET_DEPARTMENT_BY_ID: "getDepartmentById",
    GET_FACULTIES: "getFaculties",
    GET_FACULTIES_BY_DEPARTMENT: "getFacultiesByDepartment",
    GET_FACULTY_BY_ID: "getFacultyById",
    GET_DEPARTMENTS_BY_SCHOOL: "getDepartmentsBySchool",
    GET_HOD_INFO: "getHodInfo",
    GET_PROGRAM_BY_DEPARTMENT: "getProgramByDepartment",
    GET_PROGRAM_BY_ID: "getProgram",
    GET_PROGRAMS_BY_LEVEL: "getProgramsByLevel",
    GET_CAMPUS: "getCampus",
    GET_CAMPUS_BY_NAME: "getCampusByName",
    GET_ALL_PDF: "getAllPDFs",
    GET_PDFS_BY_CATEGORY: "getPdfsByCategory",
    GET_CAMPUS_BY_ZONE: "getCampusByZone",
});
